plugins {
    id 'application'
}

group = 'cookierun'
version = '1.0'

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

application {
    mainClass = 'application.CookieRunApp'
}

sourceSets {
    main {
        java { srcDirs = ['src/main/java'] }
        resources { srcDirs = ['src/main/resources'] }
    }
}

jar {
    manifest {
        attributes(
            'Main-Class': 'application.CookieRunApp'
        )
    }
}

dependencies {
    // JavaFX dependencies
    implementation 'org.openjfx:javafx-controls:11.0.3'
    implementation 'org.openjfx:javafx-fxml:11.0.3'
    implementation 'org.openjfx:javafx-graphics:11.0.3'
    implementation 'org.openjfx:javafx-base:11.0.3'
}
