@startuml
interface abilities.CookieAbility {
~ void update(GameController,Cookie,double)
}

class game.ObstacleManager {
- List<Obstacle> obstacles
- double obstacleTimer
- double nextObstacleIn
- Random rng
+ void update(double,double,List)
+ void checkCollision(Cookie,boolean[])
- void spawnObstacles(double,List)
+ List<Obstacle> getObstacles()
+ void clear()
}


class game.CollectibleManager {
- List<Collectible> collectibles
- double collectibleTimer
- double nextCollectibleIn
- Random rng
+ void update(double,double,List)
+ void checkCollision(Cookie,int[])
- void spawnCollectibles(double,List)
+ List<Collectible> getCollectibles()
+ void clear()
}


class gui.stage.StageView {
- {static} double W
- {static} double H
- {static} double GY
- CookieRunApp app
- GameController ctrl
- Canvas canvas
- int cookieIndex
- int stageIndex
- AnimationTimer loop
- long lastNano
- Image playBgImage
- Image floorImage
- double bgWidth
- double floorWidth
- double bgOff
- GameOverPane gameOverPane
- void loadStageImages()
- void bindInput()
+ void startGame()
- void draw(GraphicsContext)
- void drawSky(GraphicsContext)
- void drawGround(GraphicsContext)
- void drawHUD(GraphicsContext)
- void drawPauseOverlay(GraphicsContext)
- void buildGameOver()
- void updateGameOverLabels()
}


class utils.FrameAnimation {
- List<Image> frames
+ Image getFrame(int)
+ int size()
+ boolean isEmpty()
}


class entities.obstacles.types.airobstacles.Fireball {
+ void render(GraphicsContext)
}

class entities.stages.Stage {
- int id
- String displayName
- String worldName
- String menuBackgroundPath
- String playBackgroundPath
- String floorPath
- String jellyLogoPath
+ int getId()
+ String getDisplayName()
+ String getWorldName()
+ String getMenuBackgroundPath()
+ String getPlayBackgroundPath()
+ String getFloorPath()
+ String getJellyLogoPath()
}


class entities.cookies.implementations.PirateCookie {
}
interface utils.Collidable {
~ Rectangle2D getBounds()
~ boolean intersects(Collidable)
}

class gui.cookieSelectionPage.CookieSelectionCard {
- Cookie cookie
- int index
- StackPane iconPane
- void buildCard()
- StackPane buildIconPane()
+ int getIndex()
+ Cookie getCookie()
+ StackPane getIconPane()
}


class entities.collectibles.Coin {
- {static} double SIZE
- {static} int SCORE
# boolean isMagnetic()
+ void render(GraphicsContext)
}


class entities.obstacles.types.groundobstacles.CandyWall {
+ void render(GraphicsContext)
}

class gui.base.BaseBackgroundPane {
- Canvas canvas
- Image backgroundImage
- double offsetX
- double velocity
+ void update()
- void draw()
+ void setVelocity(double)
+ double getVelocity()
}


abstract class entities.obstacles.types.GroundObstacle {
}
class gui.base.BaseCard {
# boolean selected
# VBox upPane
# HBox downPane
# String selectedStyle
# String normalStyle
# double hoverScale
# void initializePanes(double,double)
# void initializeDefaults()
# void setupHoverEffects()
# void onHoverEnter()
# void onHoverExit()
+ void setSelected(boolean)
+ boolean isSelected()
# void applyNormalStyle()
# void applySelectedStyle()
# void applyCurrentStyle()
+ void setCustomStyles(String,String)
+ void setHoverScale(double)
}


class game.GameController {
+ {static} double GROUND_Y
+ {static} double GAME_WIDTH
- Cookie cookie
- ObstacleManager obstacleManager
- CollectibleManager collectibleManager
- HealthManager healthManager
- List<GameObject> gameObjects
- int score
- int coins
- double gameTime
- double currentSpeed
- boolean gameOver
- boolean paused
+ void onJump()
+ void onSlide()
+ void onReleaseSlide()
+ void togglePause()
+ void update(double)
+ void render(GraphicsContext)
+ int getScore()
+ int getCoins()
+ boolean isGameOver()
+ boolean isPaused()
+ Cookie getCookie()
+ double getGameTime()
+ List<GameObject> getGameObjects()
+ List<Collectible> getCollectibles()
+ void applyMagneticForceToCollectibles(MagneticAbility)
}


class entities.cookies.implementations.ZombieCookie {
}
class entities.items.HealthItem {
- double speed
+ void update(double)
+ void render(GraphicsContext)
}


class entities.cookies.implementations.NinjaCookie {
}
interface utils.Updatable {
~ void update(double)
}

class entities.cookies.implementations.BraveGingerbreadCookie {
}
class gui.cookieSelectionPage.PlayButton {
}
class entities.obstacles.types.groundobstacles.Block {
+ void render(GraphicsContext)
}

class gui.stageSelectionPage.StageSelectionCard {
- Stage stage
- int index
- StackPane logoPane
- void buildCard()
- StackPane buildLogoPane()
+ int getIndex()
+ Stage getStage()
+ StackPane getLogoPane()
}


class gui.stageSelectionPage.StagesRowPane {
- List<StageSelectionCard> cards
- int selectedIndex
- Runnable onStageSelected
- void buildStages()
- void refreshStages()
+ int getSelectedIndex()
+ void setSelectedIndex(int)
+ void setOnStageSelected(Runnable)
+ List<StageSelectionCard> getCards()
}


abstract class entities.base.GameObject {
# double x
# double y
# double width
# double height
# double velocityX
# double velocityY
# boolean alive
+ {abstract}void update(double)
+ {abstract}void render(GraphicsContext)
+ boolean collides(GameObject)
+ boolean intersects(GameObject)
+ boolean isAlive()
+ void setAlive(boolean)
+ void destroy()
+ boolean isOutOfScreen()
+ double getX()
+ double getY()
+ double getWidth()
+ double getHeight()
}


class gui.stage.GameOverPane {
- Label scoreLbl
- Label coinsLbl
- ImageView retryImg
- ImageView homeImg
- void buildPane()
+ void setOnRetry(Runnable)
+ void setOnHome(Runnable)
+ void setScore(int)
+ void setCoins(int)
}


class entities.base.Physics {
+ {static} double GRAVITY
+ {static} double JUMP_VELOCITY
+ {static} double GROUND_Y
+ {static} double NORMAL_H
+ {static} double SLIDE_H
- double x
- double y
- double velocityY
- double startX
- double startY
- double width
- double height
+ void update(double)
+ void jump()
+ void resetToGround()
+ boolean isInAir()
+ boolean isOnGround()
+ void setPosition(double,double)
+ void setX(double)
+ void setY(double)
+ void setDimensions(double,double)
+ void setHeight(double)
+ double getX()
+ double getY()
+ double getWidth()
+ double getHeight()
+ double getVelocityY()
+ void setVelocityY(double)
+ void resetToStart()
}


class entities.cookies.implementations.BlueberryCookie {
}
interface utils.Renderable {
~ void render(GraphicsContext)
}

abstract class entities.base.Cookie {
- Physics physics
- double hp
- double maxHp
- double healEffectTimer
- State state
- Image[] runFrames
- Image[] jumpFrames
- Image[] slideFrames
- Image[] deadFrames
- Image[] currentAnimationFrames
- int currentFrame
- double frameTimer
- {static} double FRAME_DUR
- Color placeholderColor
- String cookieName
# String displayName
# String tier
# String hex
# String iconPath
# int price
# boolean unlocked
# int maxHpValue
# String cookieAbilityDesc
# CookieAbility ability
- void loadAnimationFrames()
- void loadFrameSet(Image[],String)
+ void jump()
+ void slideDown()
+ void releaseSlide()
+ void die()
+ double getHp()
+ double getMaxHp()
+ void decreaseHp(double)
+ void heal(double)
+ void update(double)
+ void render(GraphicsContext)
- void drawPlaceholder(GraphicsContext)
+ void nextFrame()
+ void setAnimation(String)
+ int getCurrentFrame()
+ State getState()
+ Physics getPhysics()
+ String getDisplayName()
+ String getTier()
+ String getHex()
+ String getIconPath()
+ int getPrice()
+ boolean isUnlocked()
+ int getMaxHpValue()
+ String getCookieName()
+ void setDisplayName(String)
+ void setTier(String)
+ void setHex(String)
+ void setIconPath(String)
+ void setPrice(int)
+ void setUnlocked(boolean)
+ void setMaxHpValue(int)
+ void setHp(double)
+ void setMaxHp(int)
+ double getX()
+ double getY()
+ void setX(double)
+ void setY(double)
+ CookieAbility getAbility()
+ void setAbility(CookieAbility)
+ void reset()
}


class gui.homePage.HomePageView {
- CookieRunApp app
- BaseBackgroundPane backgroundPane
- HomePageButtonPane buttonPane
- void loadContentAsync(VBox)
}


class gui.base.BaseLabel {
# void initializeDefaults()
+ void setFont(String,int,boolean)
+ void setTextColor(String)
}

class gui.cookieSelectionPage.BackButton {
}
abstract class entities.base.Obstacle {
# double speed
+ void update(double)
# void updateBehavior(double)
+ {abstract}void render(GraphicsContext)
+ void setSpeed(double)
+ double getSpeed()
}


class gui.cookieSelectionPage.HeadingPane {
}
class gui.cookieSelectionPage.CookieSelectView {
- CookieRunApp app
- CardsRowPane cardsRowPane
- BaseBackgroundPane backgroundPane
}

class entities.obstacles.types.airobstacles.CloudSpike {
+ void render(GraphicsContext)
}

class abilities.implementations.SpeedBoostAbility {
+ void update(GameController,Cookie,double)
+ double getJumpVelocityMultiplier()
}

abstract class entities.collectibles.Collectible {
# double speed
# int scoreValue
# double glowTimer
# double magneticVelocityX
# double magneticVelocityY
+ void update(double)
+ {abstract}void render(GraphicsContext)
+ void applyMagneticForce(double,double,double,double)
+ void resetMagneticVelocity()
# boolean isMagnetic()
+ int getScoreValue()
}


enum entities.base.State {
+  RUNNING
+  JUMPING
+  SLIDING
+  DEAD
}

class gui.util.FontLoader {
+ {static} Font loadFont(String,double)
+ {static} Font getCookieRunBold(double)
}

interface utils.Spawnable {
~ boolean isAlive()
~ void setAlive(boolean)
~ double getX()
}

class gui.cookieSelectionPage.CardsRowPane {
- List<CookieSelectionCard> cards
- int selectedIndex
- Runnable onCardSelected
- void buildCards()
- void refreshCards()
+ int getSelectedIndex()
+ void setSelectedIndex(int)
+ void setOnCardSelected(Runnable)
+ List<CookieSelectionCard> getCards()
}


class abilities.implementations.MagneticAbility {
- double magneticRadius
- double attractionStrength
+ void update(GameController,Cookie,double)
+ void applyForceToCollectible(Collectible,Cookie)
+ double getMagneticRadius()
+ double getAttractionStrength()
}


class entities.cookies.CookieList {
- {static} BlueberryCookie BLUEBERRY
- {static} BraveGingerbreadCookie BRAVE_GINGERBREAD
- {static} PirateCookie PIRATE
- {static} ZombieCookie ZOMBIE
- {static} NinjaCookie NINJA
+ {static} List<Cookie> ALL
+ {static} Cookie get(int)
}


class entities.collectibles.JellyBig {
- {static} double SIZE
- {static} int SCORE
# boolean isMagnetic()
+ void render(GraphicsContext)
}


class entities.obstacles.types.groundobstacles.Spike {
+ void render(GraphicsContext)
}

interface utils.Animatable {
~ void nextFrame()
~ void setAnimation(String)
~ int getCurrentFrame()
}

class application.CookieRunApp {
+ {static} int WIDTH
+ {static} int HEIGHT
- Stage primaryStage
- int selectedCookieIndex
- int selectedStageIndex
+ void start(Stage)
+ void showHomePage()
+ void showCookieSelect()
+ void showStageSelection()
+ void startGame(int,int)
+ void startGame(int)
+ int getSelectedCookieIndex()
+ void setSelectedCookieIndex(int)
+ int getSelectedStageIndex()
+ void setSelectedStageIndex(int)
+ Stage getPrimaryStage()
+ {static} void main(String[])
}


class entities.obstacles.types.airobstacles.Bat {
+ void render(GraphicsContext)
}

class game.HealthManager {
- List<HealthItem> healthItems
- double healthSpawnTimer
- {static} double HEALTH_SPAWN_INTERVAL
+ void update(double,List)
+ void checkCollision(Cookie)
- void spawnHealthItems(List)
+ List<HealthItem> getHealthItems()
+ void clear()
}


class gui.base.BaseButton {
# double hoverScale
# Runnable onAction
# void loadImage(String)
# void setupDefaults()
# void setupHoverEffects()
# void onHoverEnter(MouseEvent)
# void onHoverExit(MouseEvent)
+ void setOnAction(Runnable)
+ void setHoverScale(double)
}


class entities.stages.StageList {
+ {static} List<Stage> ALL
+ {static} Stage getStage(int)
+ {static} List<Stage> getAllStages()
}


class gui.stageSelectionPage.StageSelectView {
- CookieRunApp app
- StagesRowPane stagesRowPane
- BaseBackgroundPane backgroundPane
}

abstract class entities.obstacles.types.AirObstacle {
# double bobTimer
# double baseY
# void updateBehavior(double)
}


class gui.base.BaseImage {
# ImageView imageView
# Canvas fallbackCanvas
# Image image
# void loadImage(String,double,double)
# void createFallback(double,double)
+ ImageView getImageView()
+ Image getImage()
+ boolean isLoaded()
}


class abilities.implementations.GhostAbility {
+ void update(GameController,Cookie,double)
}

class gui.homePage.HomePageButtonPane {
- CookieRunApp app
- ImageView letsGoButton
+ void createButtons(Image,Image)
- void addHoverEffect(ImageView)
+ ImageView getLetsGoButton()
}


class entities.collectibles.JellySmall {
- {static} double SIZE
- {static} int SCORE
# boolean isMagnetic()
+ void render(GraphicsContext)
}




gui.stage.StackPane <|-- gui.stage.StageView
entities.obstacles.types.AirObstacle <|-- entities.obstacles.types.airobstacles.Fireball
entities.base.Cookie <|-- entities.cookies.implementations.PirateCookie
gui.base.BaseCard <|-- gui.cookieSelectionPage.CookieSelectionCard
entities.collectibles.Collectible <|-- entities.collectibles.Coin
entities.obstacles.types.GroundObstacle <|-- entities.obstacles.types.groundobstacles.CandyWall
javafx.scene.layout.StackPane <|-- gui.base.BaseBackgroundPane
entities.base.Obstacle <|-- entities.obstacles.types.GroundObstacle
javafx.scene.layout.VBox <|-- gui.base.BaseCard
entities.base.Cookie <|-- entities.cookies.implementations.ZombieCookie
entities.base.GameObject <|-- entities.items.HealthItem
entities.base.Cookie <|-- entities.cookies.implementations.NinjaCookie
entities.base.Cookie <|-- entities.cookies.implementations.BraveGingerbreadCookie
gui.base.BaseButton <|-- gui.cookieSelectionPage.PlayButton
entities.obstacles.types.GroundObstacle <|-- entities.obstacles.types.groundobstacles.Block
gui.base.BaseCard <|-- gui.stageSelectionPage.StageSelectionCard
javafx.scene.layout.HBox <|-- gui.stageSelectionPage.StagesRowPane
javafx.scene.layout.Pane <|-- gui.stage.GameOverPane
entities.base.Cookie <|-- entities.cookies.implementations.BlueberryCookie
utils.Animatable <|.. entities.base.Cookie
entities.base.GameObject <|-- entities.base.Cookie
javafx.scene.layout.StackPane <|-- gui.homePage.HomePageView
javafx.scene.control.Label <|-- gui.base.BaseLabel
gui.base.BaseButton <|-- gui.cookieSelectionPage.BackButton
entities.base.GameObject <|-- entities.base.Obstacle
javafx.scene.layout.StackPane <|-- gui.cookieSelectionPage.HeadingPane
gui.cookieSelectionPage.StackPane <|-- gui.cookieSelectionPage.CookieSelectView
entities.obstacles.types.AirObstacle <|-- entities.obstacles.types.airobstacles.CloudSpike
abilities.CookieAbility <|.. abilities.implementations.SpeedBoostAbility
entities.base.GameObject <|-- entities.collectibles.Collectible
javafx.scene.layout.HBox <|-- gui.cookieSelectionPage.CardsRowPane
abilities.CookieAbility <|.. abilities.implementations.MagneticAbility
entities.collectibles.Collectible <|-- entities.collectibles.JellyBig
entities.obstacles.types.GroundObstacle <|-- entities.obstacles.types.groundobstacles.Spike
javafx.application.Application <|-- application.CookieRunApp
entities.obstacles.types.AirObstacle <|-- entities.obstacles.types.airobstacles.Bat
javafx.scene.image.ImageView <|-- gui.base.BaseButton
javafx.scene.layout.StackPane <|-- gui.stageSelectionPage.StageSelectView
entities.base.Obstacle <|-- entities.obstacles.types.AirObstacle
javafx.scene.layout.StackPane <|-- gui.base.BaseImage
abilities.CookieAbility <|.. abilities.implementations.GhostAbility
javafx.scene.layout.VBox <|-- gui.homePage.HomePageButtonPane
entities.collectibles.Collectible <|-- entities.collectibles.JellySmall
@enduml